server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 60000

# spring
spring:
  application:
    name: auth-resource

  # 数据源
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://172.16.2.53:3306/simple
    username: root
    password: 123456

  data:
    #reids配置
    redis:
      host: 172.16.2.47
      database: 0

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080

# 数据目录设置
dir:
  root: ${user.dir}/apps/${spring.application.name} # 应用文件根目录
  logs: ${dir.root}/logs # 日志文件目录

#日志配置
logging:
  file:
    path: ${dir.logs}
  level:
    root: TRACE

